foreground         #c5c7cd
background         #151d3c
background_opacity 1.0
cursor             #c5c7cd
cursor_trail_color #964bbb

active_tab_foreground     #151d3c
active_tab_background     #c5c7cd
inactive_tab_foreground   #c5c7cd
inactive_tab_background   #151d3c

active_border_color   #c5c7cd
inactive_border_color #151d3c
bell_border_color     #6b4d7a

color0       #151d3c
color8       #616883
color1       #6b4d7a
color9       #964bbb
color2       #9d4667
color10      #c46388
color3       #ceac57
color11      #d2bc87
color4       #26599a
color12      #5281bc
color5       #545c98
color13      #6975c6
color6       #a8569c
color14      #c973bc
color7       #999ba3
color15      #c5c7cd
