preload=~/Pictures/wallpapers/image6-modified.png
wallpaper=eDP-1,~/Pictures/wallpapers/image6-modified.png
splash=false


wallpaper {
monitor = eDP-1
path = ~/Pictures/wallpapers/image6-modified.png
fit_mode = cover
}
