exec-once = waybar & hyprpaper
exec-once = wal -i ~/Pictures/wallpapers/image5.jpg --cols16 darken --contrast 1.5 --saturate 0.05
exec-once =  discord --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto
# exec-once = swaync
exec-once = hyprland-autoname-workspaces
exec-once = pidof -x battery_notify.sh || ~/scripts/Battery_Notify/battery_notify.sh &
exec-once = pidof -x battery_warning.sh || ~/scripts/Battery_Notify/battery_warning.sh &
